### ISSUE TITLE
CMAKE_INSTALL_RPATH_USE_LINK_PATH does not play well with "set(CMAKE_INSTALL_RPATH" commands in Packages.cmake 

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omnitrace#121]
I ended up commenting out all of the "set(CMAKE_INSTALL_RPATH" commands, which appears to have done what I want:

```
$ readelf -d /ccs/home/nicurtis/sw/omnitrace-devel/lib/libomnitrace.so

Dynamic section at offset 0x2035d38 contains 45 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libgotcha.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libunwind.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libamdhip64.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libroctracer64.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm_amdgpu.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libnuma.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [librocprofiler64.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libhsa-runtime64.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [librocm_smi64.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libxpmem.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libomnitrace.so.1.3]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN:$ORIGIN/omnitrace:]
```

I think that `CMAKE_INSTALL_RPATH_USE_LINK_PATH` isn't playing harmoniously with those.

_Originally posted by @arghdos in https://github.com/AMDResearch/omnitrace/issues/92#issuecomment-1199910504_

**Comment by arghdos** [comment]
Sorry for all the noise @jrmadsen.  This ended up being my fix to my ongoing "can I instrument the HSA library that Omnitrace & libfabric are using".

Basically, comment out all the: "set(CMAKE_INSTALL_RPATH" commands in Packages.cmake, e.g.:
https://github.com/AMDResearch/omnitrace/blob/main/cmake/Packages.cmake#L172

IMO, this probably should be conditional on the value of "CMAKE_INSTALL_RPATH_USE_LINK_PATH".

I think once this is resolved, I should be able to instrument libfabric using the header only MPI support.

**Comment by jrmadsen** [comment]
@arghdos 

FYI, I am going to have to partially revert this for ROCm < v5.2.0. Until v5.2+, only `librocprofiler64.so` was symlinked in `/opt/rocm/lib` which bc the linker embeds the SOVERSION library name (i.e. `librocprofiler64.so.1`) this means that, basically, everyone using omnitrace would have to manually add `/opt/rocm/rocprofiler/lib` to the `LD_LIBRARY_PATH`, even just to run `omnitrace-avail`.

**Comment by arghdos** [comment]
[AMD Official Use Only - General]

Gotcha, makes sense.
________________________________
