### ISSUE TITLE
New bash versions don't like current setup-env.sh

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omnitrace#149]
https://github.com/AMDResearch/omnitrace/blob/2718596e5a6808a9278c3f6c8fddfaf977d3bcb6/cmake/Templates/setup-env.sh.in#L4

On a from-source version of Linux (running GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)), I'm seeing an issue with the current setup-env.sh where it exits with:

> "/home/amd/omnitrace does not exist"

Some light debugging, and I've found that this version of bash does not seem to like the code-pattern of:

```
BASEDIR=$(cd ${BASEDIR}/../.. && pwd)
```

Not 100% sure why (wasn't able to find any Bash 5 info on this), but:

```
BASEDIR=$(realpath ${BASEDIR}/../..)
```

seems to work insteadm

**Comment by jrmadsen** [comment]
Yeah, this should work. It’s technically not portable since realpath is a Linux command, not UNIX, e.g. there is no realpath tool on macOS, but since we don’t support macOS and don’t have any plans to do so, I’ll default to it if I can detect the exe exists
