### ISSUE TITLE
Missing path in modulefile?

### ISSUE THREAD

**Issue by jhux2** [AMDResearch/omnitrace#150]
I'm testing out `omnitrace-1.4.0-opensuse-15.3-ROCm-50200-PAPI-OMPT-Python3` on ORNL's `crusher` cluster.  After instrumenting my code, I discovered that there were some undefined symbols related to TBB:
```
        libtbb.so.2 => not found
        libtbbmalloc_proxy.so.2 => not found
        libtbbmalloc.so.2 => not found
```

I was able to fix this by adding a line to the omnitrace `1.4.0`: module file:
```
prepend-path LD_LIBRARY_PATH "${ROOT}/lib/omnitrace"
```

**Comment by ronniec91** [comment]
Thanks for reporting @jhux2 and we appreciate you trying the tool out. Looking forward to more feedback. 

This has been fixed as part of #140, also mentioned by @jrmadsen in #148. The fix will be available in v 1.5.0 release.
