### ISSUE TITLE
module file: no environment variable with absolute install path

### ISSUE THREAD

**Issue by psychocoderHPC** [AMDResearch/omnitrace#163]
As a workaround to have the HIP kernel in the trace file I need to set the environment variable

```
export HSA_TOOLS_LIB=<path to onitrace install>/omnitrace-1.6.0/rocm-5.1.0/lib/libomnitrace.so
```

The problem is that the module file is not providing a environment variable e.g. `omnitrace_ROOT` or `omnitrace_HOME` which I can use to set `HSA_TOOLS_LIB`.
Currently, I need to use`$omnitrace_DIR/../../..` which is not very elegant.

Tested with: omnitrace 1.6.0

**Comment by arghdos** [comment]
I can probably manually edit the modules on Crusher to make this work for the moment, but @jrmadsen I think all we'd need here is to change `set ROOT...` to a `setenv omnitrace_ROOT ...`

```
#%Module1.0

module-whatis "omnitrace (version 1.6.0)"

proc ModulesHelp { } {
puts stderr "Loads omnitrace v1.6.0"
}

set ROOT [file normalize [file dirname [file normalize ${ModulesCurrentModulefile}]]/../../..]

prereq "rocm/5.1.0"

prepend-path CMAKE_PREFIX_PATH "${ROOT}"
prepend-path PATH "${ROOT}/bin"
prepend-path LD_LIBRARY_PATH "${ROOT}/lib"
prepend-path PYTHONPATH "${ROOT}/lib/python/site-packages"
setenv omnitrace_DIR "${ROOT}/share/cmake/omnitrace"
```

**Comment by jrmadsen** [comment]
> I can probably manually edit the modules on Crusher to make this work for the moment, but @jrmadsen I think all we'd need here is to change `set ROOT...` to a `setenv omnitrace_ROOT ...`, e.g., from Crusher:
> 
> ```
> #%Module1.0
> 
> module-whatis "omnitrace (version 1.6.0)"
> 
> proc ModulesHelp { } {
> puts stderr "Loads omnitrace v1.6.0"
> }
> 
> ~set ROOT [file normalize [file dirname [file normalize ${ModulesCurrentModulefile}]]/../../..]~
> set omnitrace_ROOT [file normalize [file dirname [file normalize ${ModulesCurrentModulefile}]]/../../..]
> 
> prereq "rocm/5.1.0"
> 
> prepend-path CMAKE_PREFIX_PATH "${omnitrace_ROOT}"
> prepend-path PATH "${omnitrace_ROOTbin"
> prepend-path LD_LIBRARY_PATH "${omnitrace_ROOT}/lib"
> prepend-path PYTHONPATH "${omnitrace_ROOT}/lib/python/site-packages"
> setenv omnitrace_DIR "${omnitrace_ROOT}/share/cmake/omnitrace"
> ```

You don't even need to make this many edits. You can just add:

```console
setenv omnitrace_ROOT "${ROOT}"
```
