### ISSUE TITLE
RFC: Add option to instrument functions with specific calls in them

### ISSUE THREAD

**Issue by Maetveis** [AMDResearch/omnitrace#199]
As a first solution for #198 I added the option to instrument functions that have specific calls in them. I.e. instrument all functions that make a call to `bar` where `bar` can be set on the command line.

I can't think of other use-cases than #198, right now, but there might be some hence this question to check if there's interest and I should post the PR.
(For #198 I realized that may be better solved by unwinding the stack upon a trace callback)

**Comment by jrmadsen** [comment]
So I believe this could be accomplished relatively easily by inspecting the control-flow-graph dyninst provides for each function. I'll look into it and get back to you

**Comment by Maetveis** [comment]
Just to emphasize yes I know it can be done, I have a patch already would you be interested in it?

**Comment by jrmadsen** [comment]
Yeah! I love contributions, feel free to open a PR.
