### ISSUE TITLE
Can't control trace time window with --wait and --duration

### ISSUE THREAD

**Issue by sfantao** [AMDResearch/omnitrace#207]
I am trying to limit the collection of a trace to a given time window. I tried, e.g.:
```
omnitrace-sample --trace --wait 55 --duration 10 -c $wd/omnitrace.cfg -- python -u ...
```
but I always get the full trace. I was under the assumption those options were global, i.e. control sampling as well as tracing. Is this a bug or a feature? If a feature, is there a way to do limit trace collection to a given time window?

**Comment by jrmadsen** [comment]
No the duration applies only to sampling. But that shouldn't be too difficult to accommodate.

**Comment by jakurzak** [comment]
I am guessing that this is redundant with https://github.com/AMDResearch/omnitrace/issues/222

**Comment by jrmadsen** [comment]
Yeah, I will try to get this done in the next day or two now that #229 is finished
