### ISSUE TITLE
Show separate traces for different GPUs

### ISSUE THREAD

**Issue by sfantao** [AMDResearch/omnitrace#208]
When browsing a perfetto trace when multiple GPUs are being considered, I see the runtime activity separated by the different threads but the GPU activity is condensed in a single trace. I think it would be preferable to have a different trace per GPU (similar to rocprof). Otherwise the the activities show truncated and is not as insightful as it could be.

Maybe there is an option to enable that that I missed? I am running the trace collection as:
```
omnitrace-sample --trace --wait 55 --duration 10 -c $wd/omnitrace.cfg -- python -u ...
```

**Comment by jrmadsen** [comment]
I'm actually working on that right now. Should have a PR before the end of the day

**Comment by jrmadsen** [comment]
FYI, it's an extension on top of the changes in #201 -- there will be a row per-stream + per-device.
