### ISSUE TITLE
HSA operations (fill, copy) show incorrect perfetto flows

### ISSUE THREAD

**Issue by Maetveis** [AMDResearch/omnitrace#215]
As can be seen in this screenshot:

![out](https://user-images.githubusercontent.com/8176760/202692784-d113f78e-6e58-4e88-a4b4-ef8b511306d8.png)

Produced with the `transpose` example, using binary rewrite. In the same trace, the copy operations on the first Queue correctly point to the HIP API calls that enqueued them.

Omnitrace version: `v1.7.3`
ROCm version: `5.3.3`

**Comment by jrmadsen** [comment]
Yeah, I've noticed this issue too. Haven't decided how I want to handle it bc it appears to simply be an internal roctracer issue with the correlation IDs provided by roctracer
