### ISSUE TITLE
DYNINST_BUILD_BOOST: build fails to start with ninja

### ISSUE THREAD

**Issue by Maetveis** [AMDResearch/omnitrace#219]
With the following configuration:
```plaintext
cmake -S -B build -G Ninja
-DDYNINST_BUILD_BOOST="ON" \
-DDYNINST_BUILD_ELFUTILS="ON" \
-DDYNINST_BUILD_LIBIBERTY="ON" \
-DDYNINST_BUILD_TBB="ON" \
-DOMNITRACE_BUILD_DYNINST="ON" \
-DOMNITRACE_USE_MPI="ON" \
-DOMNITRACE_USE_MPI_HEADERS="OFF" \
-DOMNITRACE_USE_PYTHON="OFF" \
-DOMNITRACE_USE_ROCM_SMI="ON" \
-DOMNITRACE_USE_ROCTRACER="ON" \
-DOMNITRACE_MPI_IMPL="openmpi" \
-DCMAKE_PREFIX_PATH="/opt/rocm;/usr/local"
```

with rocm 5.3.3

Starting the build (i.e. `cmake --build build`, or `cd build; ninja`) fails with the following error:
```console
❯ ninja -j60
ninja: error: 'external/dyninst/tpls/lib/libboost_atomic.a', needed by 'external/dyninst/dyninstAPI_RT/libdyninstAPI_RT.so.11.0.1', missing and no known rule to make it
```

The same configuration works correctly when makefiles are used.

I am reporting this here, because I saw that omnitrace has its own fork of `dyninst` with some modifications to the cmake files, let me know if this should be instead directed upstream.

**Comment by jrmadsen** [comment]
No, this is an issue specific to ninja and externalproject_add. Ninja doesn't use variables so it notices a library doesn't exist immediately whereas makefiles evaluate the dependency after the dependency has been built. If you build the `dyninst-external-libraries` target the very first time after configuring, all subsequent runs of ninja will work. It's just a matter of making sure those files exist. In many cases, I actually just create an empty file during the CMake configuration to fool ninja into thinking it exists but Boost is a pain w.r.t. dependencies and I haven't deployed this technique for it.
