### ISSUE TITLE
Missing Information for some Memory Operations (host to device or device to host)

### ISSUE THREAD

**Issue by dwchang79** [AMDResearch/omnitrace#310]
Some of my omnitrace proto files do not have the complete information on all memory operations. For example, if there is a hipMemcpy at the end from device to host, it does not show that information. I am using the following database call to find all instances:

SELECT caller_slice.name AS caller_name, caller_slice.ts AS caller_ts, caller_slice.dur AS caller_dur, caller_slice.id AS caller_id, caller_slice.name AS caller_name, caller_slice.track_id AS caller_track_id, callee_slice.ts AS callee_ts, callee_slice.dur AS callee_dur, callee_slice.id AS callee_id, callee_slice.name AS callee_name, callee_slice.track_id AS callee_track_id FROM (slice AS caller_slice JOIN flow ON caller_slice.id = flow.slice_out) JOIN slice AS callee_slice ON callee_slice.id = flow.slice_in

I think this means some of the memory operations do not have a caller or callee. I have checked the corresponding rocTracer file and it does have this information. I think something is not being picked up or lost. Or maybe it is simpler and I just need a different SQL query? 

I cannot attach the proto file, but have attached the roctracer file where you can see that the hipMemcpy is in there. I will take a screenshot of what I am seeing in Perfetto. Hopefully you can see in Perfetto screen capture that the very last hipMemcpy does not link anywhere while the hipMemset does. 

Thank you. 
[roctracer-61388.txt](https://github.com/AMDResearch/omnitrace/files/12783884/roctracer-61388.txt)
![hipmemcpy](https://github.com/AMDResearch/omnitrace/assets/142359348/dfd382c4-e21b-45b1-9807-b55d314fee44)
![hipmemset](https://github.com/AMDResearch/omnitrace/assets/142359348/f620ee0f-e3ee-454c-90ef-e362e07db168)

**Comment by jrmadsen** [comment]
This is likely going to be solved by the changes in #317

**Comment by jrmadsen** [comment]
Please re-open if #317 does not fix this issue in the upcoming release
