### ISSUE TITLE
[Issue]: Mode based index may not be properly configured

### ISSUE THREAD

**Issue by aymane-eljerari** [AMDResearch/omnitrace#404]
### Problem Description

When trunning `omnitrace-sample`, i get the following error:

```
[omnitrace][600160][0][omnitrace_init] omnitrace_init(mode=sampling, is_binary_rewrite=false, argv0=/app/llama.cpp/llama-bench) called after omnitrace was initialized. state = Active. Mode-based settings (via -M <MODE> passed to omnitrace exe) may not be properly configured.
```

### Operating System

Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### CPU

AMD EPYC 7H12 64-Core Processor

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 6.2.0

**Comment by ppanchad-amd** [comment]
Hi @aymane-eljerari. Internal ticket has been created to investigate your issue. Thanks!

**Comment by schung-amd** [comment]
Hi @aymane-eljerari, how are you invoking `omnitrace-sample`? I can't reproduce this with the latest release of omnitrace (for ROCm 6.2.2) when running the `omnitrace-sample` example invocation in the docs (https://rocm.docs.amd.com/projects/omnitrace/en/latest/how-to/sampling-call-stack.html#an-omnitrace-sample-example).

**Comment by aymane-eljerari** [comment]
I am invoking omnitrace-sample inside a bash script like this:
```
omnitrace-sample -c /app/llm-prof-utils/.omnitrace.cfg --o ../omnitrace_output/${quant}_${split_mode} -TPHD --trace-file $quant-pp512-tg128.proto -- \
  $bench_command
```

**Comment by schung-amd** [comment]
Can you post the contents of your `omnitrace.cfg` file?

**Comment by aymane-eljerari** [comment]
This is the `.omnitrace.cfg` file I'm using:

```
$ENABLE                             = ON
$SAMPLE                             = OFF

# use fields
OMNITRACE_TRACE                     = $ENABLE
OMNITRACE_PROFILE                   = $ENABLE
OMNITRACE_USE_SAMPLING              = $SAMPLE
OMNITRACE_USE_PROCESS_SAMPLING      = $SAMPLE

# debug
OMNITRACE_DEBUG                     = OFF
OMNITRACE_VERBOSE                   = 1

# output fields
OMNITRACE_CONFIG_FILE               = /app/llm-prof-utils/.omnitrace.cfg
OMNITRACE_ENABLED                   = true
OMNITRACE_OUTPUT_PATH               = omnitrace-output
OMNITRACE_OUTPUT_PREFIX             = %tag%/
OMNITRACE_TIME_OUTPUT               = OFF
OMNITRACE_USE_PID                   = OFF

# sampling fields
OMNITRACE_USE_THREAD_SAMPLING       = true
OMNITRACE_SAMPLING_FREQ             = 50
OMNITRACE_SAMPLING_DELAY            = 0.1
OMNITRACE_SAMPLING_CPUS             = all
OMNITRACE_SAMPLING_GPUS             = $env:HIP_VISIBLE_DEVICES

# perfetto
OMNITRACE_USE_PERFETTO              = true
OMNITRACE_PERFETTO_BACKEND          = inprocess
OMNITRACE_PERFETTO_BUFFER_SIZE_KB   = 2000000
OMNITRACE_PERFETTO_FILL_POLICY      = ring_buffer

OMNITRACE_PROCESS_SAMPLING_FREQ     = 50
OMNITRACE_USE_ROCPROFILER           = true
OMNITRACE_ROCM_EVENTS               = ​Mem​Unit​Busy Mem​Unit​Stalled VALUBusy
OMNITRACE_USE_ROCTRACER             = true
OMNITRACE_USE_ROCM_SMI              = true
```

**Comment by schung-amd** [comment]
Are you doing any other omnitrace work in that script? I can't reproduce this when using `omnitrace-sample` with your config file and options, so I'm wondering if this could be resulting from something else happening upstream. Also, are you sampling a binary that has been instrumented with `omnitrace-instrument`? Looking through the source code I see a path that might result in this error, although I didn't see the error in practice when I tried this.

**Comment by jrmadsen** [comment]
This looks more like a warning than an error. Are you getting a failure?

The contents of that warning message might need to be re-evaluated bc I believe it is omnitrace-instrument that has the -M option and I think the -M option is a legacy option that became unnecessary between requiring omnitrace-run for instrumented executables and the creation of omnitrace-sample, i.e. formerly omnitrace-instrument had a -M option which basically just instrumented calls before and after main which started/stopped sampling. Once omnitrace-sample came along, it uses an LD_PRELOAD of libomnitrace-dl.so to wrap main; completely removing the need to use omnitrace-instrument to sample an uninstrumented exe.

**Comment by aymane-eljerari** [comment]
I didn't get any failures when runing `omnitrace-sample`.  I though the message would affect the my sampling results. Thanks for the explanation!
