### ISSUE TITLE
[Feature]: Adjust CI to include quick start installer script

### ISSUE THREAD

**Issue by wyphan** [AMDResearch/omnitrace#407]
### Suggestion Description

For some reason, the CI-built [rocm-6.2.2][tag] release tag doesn't include the `omnitrace-install.py` script as one of the release artifacts. This tag is newer than the Omnitrace v1.12.0 release tag, which properly has the script. Now, this becomes an issue because the quick start installation guide in both `README.md` and the [docs][docs] relies on downloading the script from the "latest" tag. At the time of writing, the URL is broken because "latest" points to "rocm-6.2.2", and the script is missing on that release tag.

It would be a good idea to adjust the ROCm CI release bot to include and/or generate the `omnitrace-install.py` script.

[tag]: https://github.com/ROCm/omnitrace/releases/tag/rocm-6.2.2
[docs]: https://rocm.docs.amd.com/projects/omnitrace/en/latest/install/quick-start.html

**Comment by dgaliffiAMD** [comment]
Thanks, @wyphan . 
This should be fixed with https://github.com/ROCm/omnitrace/pull/400. Our next release from rocm-6.2.x should work as expected. 
Thanks for the feedback.
