### ISSUE TITLE
Any way to configure width of Timemory output?

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omnitrace#41]
e.g., 

![image](https://user-images.githubusercontent.com/6463881/173426794-c22e49b4-d4d7-4a11-b3b8-828ab66153a4.png)

the kernel name is getting ellipsed (totally a verb) before I can see the relevant name.  I imagine the "right" way to do this is to hook-up with KokkosP to rename the kernels, however it would be good to add (or document, if one exists already) a method to control the width of these tables.

**Comment by jrmadsen** [comment]
OMNITRACE_MAX_WIDTH

Also, the kernel names are not truncated in the JSON outputs.

**Comment by jrmadsen** [comment]
`omnitrace-avail -db -r WIDTH`

**Comment by arghdos** [comment]
Sigh, my reading comprehension ... :rofl:
