### ISSUE TITLE
[Issue]: Compilation error related to Dyninst 13.0.0

### ISSUE THREAD

**Issue by xaguilar** [AMDResearch/omnitrace#421]
### Problem Description

When I try to compile omnitrace from source I encounter compilation errors against the dyninst submodule. Dyninst 13.0.0 has an API change for Module::getAllFunctions. 

I get this compilation error:

/cfs/klemming/home/xaguilar/omnitrace/omnitrace-source/source/bin/omnitrace-instrument/details.cpp: In function ‘void process_modules(const std::vector<BPatch_module*, std::allocator<BPatch_module*> >&)’:
/cfs/klemming/home/xaguilar/omnitrace/omnitrace-source/source/bin/omnitrace-instrument/details.cpp:815:33: error: no matching function for call to ‘Dyninst::SymtabAPI::Module::getAllFunctions(std::map<Dyninst::SymtabAPI::Module*, std::vector<Dyninst::SymtabAPI::Function*> >::mapped_type&)’
  815 |         if(!itr->getAllFunctions(symtab_data.functions.at(itr))) continue;
      |             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/Symtab.h:44,
                 from /cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/Variable.h:38,
                 from /cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/BPatch_type.h:40,
                 from /cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/BPatch_image.h:37,
                 from /cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/BPatch_thread.h:37,
                 from /cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/BPatch.h:37,
                 from /cfs/klemming/home/xaguilar/omnitrace/omnitrace-source/source/bin/omnitrace-instrument/fwd.hpp:39,
                 from /cfs/klemming/home/xaguilar/omnitrace/omnitrace-source/source/bin/omnitrace-instrument/function_signature.hpp:25,
                 from /cfs/klemming/home/xaguilar/omnitrace/omnitrace-source/source/bin/omnitrace-instrument/details.cpp:23:
/cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/Module.h:84:28: note: candidate: ‘std::vector<Dyninst::SymtabAPI::Function*> Dyninst::SymtabAPI::Module::getAllFunctions() const’
   84 |     std::vector<Function*> getAllFunctions() const;
      |                            ^~~~~~~~~~~~~~~
/cfs/klemming/home/xaguilar/omnitrace/dependencies/dyninst/install/include/Module.h:84:28: note:   candidate expects 0 arguments, 1 provided

### Operating System

SLES 15-SP5

### CPU

AMD EPYC 7A53 64-Core Processor

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 5.7.0

### Additional Information

I'm using g++-12 (SUSE Linux) 12.3.0

**Comment by ppanchad-amd** [comment]
Hi @xaguilar. Internal ticket has been created to investigate your issue. Thanks!

**Comment by darren-amd** [comment]
Hi @xaguilar,

How are you installing omnitrace? Are you installing according to the installation instructions [here](https://rocm.docs.amd.com/projects/omnitrace/en/latest/install/install.html#installing-omnitrace)? If so, could you please try again on the latest version of ROCm (6.2.4) and let me know if the issue persists? (Please make sure to uninstall the older version: [Uninstall Instructions](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/amdgpu-install.html#uninstalling-rocm)) Thanks!

**Comment by xaguilar** [comment]
Hi @darren-amd ,

I'm compiling omnitrace from scratch, so cloning the repo and compiling. Yes, I followed the instructions from that page. First I installed the dependencies (Dynisnt, TBB, etc) either by hand or with Spack (tried both), and then I compiled omnitrace. 

The error appears when omnitrace is compiling the instrumentation part  that uses Dyninst. It throws a compilation error because in Dyninst 13.0.0 there's been an API change of some calls you guys use in omnitrace. I tried using dyninst 12.3.0 and then it compiles without problems. 

Since the error comes from some Dyninst calls within omnitrace, what difference would make changing the ROCm version? In any case, I'm compiling omnitrace on a Cray so I can't change the ROCm version myself unfortunately. The latest we have is 5.7.0.

I'm already using omnitrace coupled with Dyninst 12.3.0 so everything is fine. I just wanted to warn you guys about this issue. 

Thanks a lot in advance!

**Comment by darren-amd** [comment]
Hi @xaguilar,

Thanks for bringing this up! I spoke with the internal team and there is an ongoing initiative to update the Dyninst submodule to add support for the latest version (https://github.com/ROCm/omnitrace/issues/303). I currently do not have a timeline for this, but in the meantime please continue to use the older versions of Dyninst, and feel free to let me know if you run into any issues. Thanks!

**Comment by xaguilar** [comment]
Alright, sounds good! Thanks!
