### ISSUE TITLE
[Issue]: Proto file causes error in ui.perfetto.dev

### ISSUE THREAD

**Issue by rlorigro** [AMDResearch/omnitrace#422]
### Problem Description

I ran the `omnitrace-sample` executable from the `omnitrace-1.11.2-ubuntu-22.04-PAPI-OMPT-Python3` installer with no arguments, just my own C++ executable+args, then it exits normally:

```
...
[omnitrace][8461][0][omnitrace_finalize] Finalizing perfetto...
[omnitrace][8461][perfetto]> Outputting '/home/.../omnitrace-annotate-output/2024-12-04_08.37/perfetto-trace-8461.proto' (42908.89 KB / 42.91 MB / 0.04 GB)... Done
[omnitrace][8461][metadata]> Outputting 'omnitrace-annotate-output/2024-12-04_08.37/metadata-8461.json' and 'omnitrace-annotate-output/2024-12-04_08.37/functions-8461.json'
[omnitrace][8461][0][omnitrace_finalize] Finalized: 2.874768 sec wall_clock,  374.208 MB peak_rss, -299.405 MB page_rss, 2.930000 sec cpu_clock,  101.9 % cpu_util
[387.781]       perfetto.cc:60128 Tracing session 1 ended, total sessions:0
```

But when I attempt to use ui.perfetto.dev to load the proto file, it fails and returns this error:
```
Oops, something went wrong. Please file a bug.
UI: https://ui.perfetto.dev/v47.0-1b4776303

Unknown field type

Trace: not available (FILE). Provide repro steps.
UA: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
Referrer: 
```

### Operating System

NAME="Ubuntu" VERSION="22.04.5 LTS (Jammy Jellyfish)"

### CPU

AMD Ryzen Threadripper 1950X 16-Core Processor

### GPU

None

### ROCm Version

ROCm 6.2.3

### Steps to Reproduce

I am happy to send the output files if there is an appropriate way to do it

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

bash: /opt/rocm/bin/rocminfo: No such file or directory

**Comment by ppanchad-amd** [comment]
Hi @rlorigro. Internal ticket has been created to investigate your issue. Thanks!

**Comment by jrmadsen** [comment]
@rlorigro Omnitrace was rebranded to ROCm Systems Profiler and a fix for this issue is being addressed here: https://github.com/ROCm/rocprofiler-systems/pull/30

in the meantime, somewhere in the docs, there should be browser link to an older release of ui.perfetto.dev which can still load them.  

@dgaliffiAMD

**Comment by jrmadsen** [comment]
@rlorigro Ah, actually, if you upgrade to v1.13.0, this is already fixed in Omnitrace: https://github.com/ROCm/omnitrace/releases/tag/v1.13.0 via #411

**Comment by rlorigro** [comment]
Awesome thank you for the quick response, and sorry for missing that. I will try it tomorrow

**Comment by rlorigro** [comment]
Using v1.13.0 (and also the latest rebranded release), It loads now and for the most part looks very nice in the browser, but it seems that it is only reporting threads 0 and 1, despite there being 32 child threads launched (implemented in C++ with pthread).

Invoking `--trace` or `--profile` options result in the program not executing at all, which is also confusing.

Honestly I mostly care about summary stats, and less about the timeline. Probably I am doing something wrong?
![image](https://github.com/user-attachments/assets/8b12d293-7a5b-4fda-b5c0-4247229ee9d9)
![image](https://github.com/user-attachments/assets/8d21e3a6-475c-4d44-99e0-18833983ba1a)
